### ISSUE TITLE
Update Docker-Compose for the web app to wait until database is up and running

### ISSUE THREAD

**Issue by sehmuzc** [sehmuzc/Boun1#40]
When the database is not up, the web app should not start and wait until the db is properly functioning.

**Comment by sehmuzc** [comment]
Healthcheck part has been added.
```
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
```

#43
